### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by boa-cp** [trlsmax/imgui-vtk#16]
This project has no license, thus it can't be used in any software

**Comment by rajkundu** [comment]
@trlsmax Do you have any preference? As far as I am aware, [ImGui has an MIT license](https://github.com/ocornut/imgui/blob/master/LICENSE.txt), and [VTK has a BSD 3-clause license](https://gitlab.kitware.com/vtk/vtk/-/tree/master#license). They both seem to be extremely similar (see "BSD 3-Clause License vs. the MIT License" [on this blog post](https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license)) and very permissive.

Since imgui-vtk is an extension - not a redistribution or repackaging - of ImGui/VTK, I think you can use almost any license. If you are open to suggestions, I think assigning an MIT license to this repo through GitHub would be a good, quick, and easy option.

**Comment by boa-cp** [comment]
Dear Raj,

Thank you for the answer. The issue is that the license should be
explicitly mentioned in the repository of the code.
The code licence can't be deduced from any source but should be
explicitly mentioned/defined.
Could you put the license you want in the repository? Otherwise,
the code is supposed to be private and it means that any use is illegal.
I think the MIT licence is an excellent choice.

regards
Igal

**Comment by rajkundu** [comment]
Hi Igal,

I agree with you and understand your concerns. Unfortunately, I do not have write privileges to this repository and cannot assign the license myself; only @trlsmax currently has the ability to do so.

**Comment by boa-cp** [comment]
Thank you. Thus there is no solution :)

**Comment by rajkundu** [comment]
I think the omission of a license in this repository was merely an oversight, not an indication of copyright ownership. The point of collaborating and publishing code publicly, on GitHub, is for others to benefit, and I think the others contributors `imgui-vtk` would agree. However, since I cannot be 100% sure of anything, we are a bit stuck until they can provide their explicit consent.

Now, the changes I made to `imgui-vtk` in [my own fork](https://github.com/rajkundu/imgui-vtk) removed pretty much everything except the VtkViewer class, which I then upgraded in a few ways. As far as I understand, @MorcilloSanz single-handedly wrote the original version of the VtkViewer class. @MorcilloSanz, would you be agreeable to an MIT license for your contributions? If so, I am happy to make my fork MIT-licensed so that people can continue to use `imgui-vtk` until we resolve this issue here.

**Comment by MorcilloSanz** [comment]
Hello,

Yes, I was who wrote the first implementation of VtkViewer class and I also think the purpose of this repository is for others benefit
I also think the MIT license is the best choice (at least is the one that I prefer), so if you want, go ahead. 
But @trlsmax has to accept the pull request.

Best whises!

**Comment by rajkundu** [comment]
@MorcilloSanz Thank you for your prompt response! I have added the MIT License to my repository, so everyone is free to use [my fork of imgui-vtk](https://github.com/rajkundu/imgui-vtk) accordingly.

Importantly, with the merging of #14, trlsmax/imgui-vtk is now _based on_ my fork - not the other, more usual, way around. Thus, both repositories now entirely consist of code written by either @MorcilloSanz or me, both of whom have agreed to use of the MIT license.

**Comment by boa-cp** [comment]
Raj and Alberto,

Thank you very much for the solution!

regards
Igal

**Comment by rajkundu** [comment]
Max kindly gave me permission to be a contributor to this repository as well as to officially give it an MIT license. So, this issue should be fixed by 176ce5a. Thank you for bringing it to our attention, @boa-cp!
