### ISSUE TITLE
Using vcpkg

### ISSUE THREAD

**Issue by PetiteViking** [trlsmax/imgui-vtk#9]
Hi,
GLFW3 and ImGui are available through vcpkg. Would you be interested in using vcpkg for dependency management for this project? If so, I can go ahead and create a PR.

**Comment by trlsmax** [comment]
Hi, thanks.
But not every one use VS, and some of them don't even work on Windows.
In the future we can remove all dependency from this repo and provide vcpkg package or cmake module to help people install this lib into their project easily.

**Comment by JochenJankowai** [comment]
The nice thing about vcpkg is that it is cross-platform and IDE agnostic. It runs on Linux, Windows and Mac.

**Comment by pwm1234-sri** [comment]
@JochenJankowai What would you put in a PR for this example using vcpkg? I did not encounter any problems using the vcpkg toolchain file with this example. The only think I think would be helpful are a few statements in the readme saying what packages need to be installed and the trivial step (which should be well known) of including the vcpkg toolchain file when doing cmake configure. Otherwise, the find_package cmake commands worked great for me.

**Comment by rajkundu** [comment]
Closing as CMake support now exists. Please feel free to comment/reopen/etc. if vcpkg support is still of strong interest to you!
